authority_weights:
  baseline_credentials: 0.4
  track_record: 0.4
  recent_performance: 0.2
track_record:
  update_factor: 0.05
thresholds:
  disagreement: 0.3
baseline_credentials:
  types:
    ACADEMIC_DEGREE:
      weight: 0.3
      scoring_function:
        type: map
        values:
          Bachelor: 1.0
          LLM: 1.1
          JD: 1.2
          PhD: 1.5
        expression: ''
        default: 0.0
