authority_weights:
  baseline_credentials: 0.3
  track_record: 0.5
  recent_performance: 0.2
track_record:
  update_factor: 0.05
thresholds:
  disagreement: 0.4
baseline_credentials:
  types:
    ACADEMIC_DEGREE:
      weight: 0.3
      scoring_function:
        type: map
        values:
          Bachelor: 1.0
          LLM: 1.1
          JD: 1.2
          PhD: 1.5
        expression: ''
        default: 0.0
    PROFESSIONAL_EXPERIENCE:
      weight: 0.4
      scoring_function:
        type: formula
        values: {}
        expression: 0.5 + 0.2 * sqrt(value)
        default: 0.0
    PUBLICATION:
      weight: 0.2
      scoring_function:
        type: formula
        values: {}
        expression: min(0.8 + 0.1 * value, 1.4)
        default: 0.0
    INSTITUTIONAL_ROLE:
      weight: 0.1
      scoring_function:
        type: map
        values:
          Junior: 0.7
          Senior: 1.1
          Partner: 1.4
          default: 0.0
        expression: ''
        default: 0.0
